version: '3.9'
services:
  db:
    image: postgres
    restart: always
    ports:
        - 5433:5432
    volumes:
        - my_pg_v:/var/lib/postgresql/data/
    environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_USER=${DB_USER}

volumes:
  my_pg_v:

networks:
  default:
    name: backend

